# Generated by Django 4.1.5 on 2023-01-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0002_alter_branch_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
