# Generated by Django 4.1.5 on 2023-01-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0003_alter_branch_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='date_created',
            new_name='join_date',
        ),
    ]
