# Generated by Django 4.1.5 on 2023-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PMS", "0004_rename_date_created_branch_join_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="branch",
            old_name="branchname",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="dir_branch",
        ),
        migrations.AddField(
            model_name="branch",
            name="directorates",
            field=models.ManyToManyField(to="PMS.directorate"),
        ),
    ]
